1.2.8 Release candidate
git-svn-id: https://svn.qdecoder.org/qhttpd/trunk@175 915dc90f-ddda-dc11-960a-0015c5f490bc

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -3806,8 +3806,8 @@ fi
 if test $ac_cv_header_qDecoder_h = yes; then
   :
 else
-  { { echo "$as_me:$LINENO: error: qDecoder library 10.1.4 or above must be installed." >&5
-echo "$as_me: error: qDecoder library 10.1.4 or above must be installed." >&2;}
+  { { echo "$as_me:$LINENO: error: qDecoder library 10.1.6 or above must be installed." >&5
+echo "$as_me: error: qDecoder library 10.1.6 or above must be installed." >&2;}
    { (exit 1); exit 1; }; }
 fi
 
@@ -3879,8 +3879,8 @@ _ACEOF
   LIBS="-lqDecoder $LIBS"
 
 else
-  { { echo "$as_me:$LINENO: error: qDecoder library 10.1.4 or above must be installed." >&5
-echo "$as_me: error: qDecoder library 10.1.4 or above must be installed." >&2;}
+  { { echo "$as_me:$LINENO: error: qDecoder library 10.1.6 or above must be installed." >&5
+echo "$as_me: error: qDecoder library 10.1.6 or above must be installed." >&2;}
    { (exit 1); exit 1; }; }
 fi
 
