Make it compatible with qLibc
git-svn-id: https://svn.qdecoder.org/qhttpd/trunk@187 915dc90f-ddda-dc11-960a-0015c5f490bc

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -2312,7 +2312,7 @@ ac_compiler_gnu=$ac_cv_c_compiler_gnu
 if test $ac_compiler_gnu = yes; then
 	CFLAGS="-Wall"
 #else
-#	AC_MSG_FAILURE([GCC is required to compile qDecoder.])
+#	AC_MSG_FAILURE([GCC is required to compile qHttpd.])
 fi
 
 ac_aux_dir=
@@ -3666,18 +3666,18 @@ fi
 OPT_OBJS=""
 
 ## Checks for 3rd libraries.
-if test "${ac_cv_header_qDecoder_h+set}" = set; then
-  echo "$as_me:$LINENO: checking for qDecoder.h" >&5
-echo $ECHO_N "checking for qDecoder.h... $ECHO_C" >&6
-if test "${ac_cv_header_qDecoder_h+set}" = set; then
+if test "${ac_cv_header_qlibc_h+set}" = set; then
+  echo "$as_me:$LINENO: checking for qlibc.h" >&5
+echo $ECHO_N "checking for qlibc.h... $ECHO_C" >&6
+if test "${ac_cv_header_qlibc_h+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 fi
-echo "$as_me:$LINENO: result: $ac_cv_header_qDecoder_h" >&5
-echo "${ECHO_T}$ac_cv_header_qDecoder_h" >&6
+echo "$as_me:$LINENO: result: $ac_cv_header_qlibc_h" >&5
+echo "${ECHO_T}$ac_cv_header_qlibc_h" >&6
 else
   # Is the header compilable?
-echo "$as_me:$LINENO: checking qDecoder.h usability" >&5
-echo $ECHO_N "checking qDecoder.h usability... $ECHO_C" >&6
+echo "$as_me:$LINENO: checking qlibc.h usability" >&5
+echo $ECHO_N "checking qlibc.h usability... $ECHO_C" >&6
 cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
 _ACEOF
@@ -3685,7 +3685,7 @@ cat confdefs.h >>conftest.$ac_ext
 cat >>conftest.$ac_ext <<_ACEOF
 /* end confdefs.h.  */
 $ac_includes_default
-#include <qDecoder.h>
+#include <qlibc.h>
 _ACEOF
 rm -f conftest.$ac_objext
 if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
@@ -3721,15 +3721,15 @@ echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
 echo "${ECHO_T}$ac_header_compiler" >&6
 
 # Is the header present?
-echo "$as_me:$LINENO: checking qDecoder.h presence" >&5
-echo $ECHO_N "checking qDecoder.h presence... $ECHO_C" >&6
+echo "$as_me:$LINENO: checking qlibc.h presence" >&5
+echo $ECHO_N "checking qlibc.h presence... $ECHO_C" >&6
 cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
 _ACEOF
 cat confdefs.h >>conftest.$ac_ext
 cat >>conftest.$ac_ext <<_ACEOF
 /* end confdefs.h.  */
-#include <qDecoder.h>
+#include <qlibc.h>
 _ACEOF
 if { (eval echo "$as_me:$LINENO: \"$ac_cpp conftest.$ac_ext\"") >&5
   (eval $ac_cpp conftest.$ac_ext) 2>conftest.er1
@@ -3763,25 +3763,25 @@ echo "${ECHO_T}$ac_header_preproc" >&6
 # So?  What about this header?
 case $ac_header_compiler:$ac_header_preproc:$ac_c_preproc_warn_flag in
   yes:no: )
-    { echo "$as_me:$LINENO: WARNING: qDecoder.h: accepted by the compiler, rejected by the preprocessor!" >&5
-echo "$as_me: WARNING: qDecoder.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
-    { echo "$as_me:$LINENO: WARNING: qDecoder.h: proceeding with the compiler's result" >&5
-echo "$as_me: WARNING: qDecoder.h: proceeding with the compiler's result" >&2;}
+    { echo "$as_me:$LINENO: WARNING: qlibc.h: accepted by the compiler, rejected by the preprocessor!" >&5
+echo "$as_me: WARNING: qlibc.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
+    { echo "$as_me:$LINENO: WARNING: qlibc.h: proceeding with the compiler's result" >&5
+echo "$as_me: WARNING: qlibc.h: proceeding with the compiler's result" >&2;}
     ac_header_preproc=yes
     ;;
   no:yes:* )
-    { echo "$as_me:$LINENO: WARNING: qDecoder.h: present but cannot be compiled" >&5
-echo "$as_me: WARNING: qDecoder.h: present but cannot be compiled" >&2;}
-    { echo "$as_me:$LINENO: WARNING: qDecoder.h:     check for missing prerequisite headers?" >&5
-echo "$as_me: WARNING: qDecoder.h:     check for missing prerequisite headers?" >&2;}
-    { echo "$as_me:$LINENO: WARNING: qDecoder.h: see the Autoconf documentation" >&5
-echo "$as_me: WARNING: qDecoder.h: see the Autoconf documentation" >&2;}
-    { echo "$as_me:$LINENO: WARNING: qDecoder.h:     section \"Present But Cannot Be Compiled\"" >&5
-echo "$as_me: WARNING: qDecoder.h:     section \"Present But Cannot Be Compiled\"" >&2;}
-    { echo "$as_me:$LINENO: WARNING: qDecoder.h: proceeding with the preprocessor's result" >&5
-echo "$as_me: WARNING: qDecoder.h: proceeding with the preprocessor's result" >&2;}
-    { echo "$as_me:$LINENO: WARNING: qDecoder.h: in the future, the compiler will take precedence" >&5
-echo "$as_me: WARNING: qDecoder.h: in the future, the compiler will take precedence" >&2;}
+    { echo "$as_me:$LINENO: WARNING: qlibc.h: present but cannot be compiled" >&5
+echo "$as_me: WARNING: qlibc.h: present but cannot be compiled" >&2;}
+    { echo "$as_me:$LINENO: WARNING: qlibc.h:     check for missing prerequisite headers?" >&5
+echo "$as_me: WARNING: qlibc.h:     check for missing prerequisite headers?" >&2;}
+    { echo "$as_me:$LINENO: WARNING: qlibc.h: see the Autoconf documentation" >&5
+echo "$as_me: WARNING: qlibc.h: see the Autoconf documentation" >&2;}
+    { echo "$as_me:$LINENO: WARNING: qlibc.h:     section \"Present But Cannot Be Compiled\"" >&5
+echo "$as_me: WARNING: qlibc.h:     section \"Present But Cannot Be Compiled\"" >&2;}
+    { echo "$as_me:$LINENO: WARNING: qlibc.h: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: qlibc.h: proceeding with the preprocessor's result" >&2;}
+    { echo "$as_me:$LINENO: WARNING: qlibc.h: in the future, the compiler will take precedence" >&5
+echo "$as_me: WARNING: qlibc.h: in the future, the compiler will take precedence" >&2;}
     (
       cat <<\_ASBOX
 ## --------------------------------------- ##
@@ -3792,34 +3792,34 @@ _ASBOX
       sed "s/^/$as_me: WARNING:     /" >&2
     ;;
 esac
-echo "$as_me:$LINENO: checking for qDecoder.h" >&5
-echo $ECHO_N "checking for qDecoder.h... $ECHO_C" >&6
-if test "${ac_cv_header_qDecoder_h+set}" = set; then
+echo "$as_me:$LINENO: checking for qlibc.h" >&5
+echo $ECHO_N "checking for qlibc.h... $ECHO_C" >&6
+if test "${ac_cv_header_qlibc_h+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
-  ac_cv_header_qDecoder_h=$ac_header_preproc
+  ac_cv_header_qlibc_h=$ac_header_preproc
 fi
-echo "$as_me:$LINENO: result: $ac_cv_header_qDecoder_h" >&5
-echo "${ECHO_T}$ac_cv_header_qDecoder_h" >&6
+echo "$as_me:$LINENO: result: $ac_cv_header_qlibc_h" >&5
+echo "${ECHO_T}$ac_cv_header_qlibc_h" >&6
 
 fi
-if test $ac_cv_header_qDecoder_h = yes; then
+if test $ac_cv_header_qlibc_h = yes; then
   :
 else
-  { { echo "$as_me:$LINENO: error: qDecoder library 10.1.6 or above must be installed." >&5
-echo "$as_me: error: qDecoder library 10.1.6 or above must be installed." >&2;}
+  { { echo "$as_me:$LINENO: error: qLibc library 1.0.0 or above must be installed. http://www.qdecoder.org" >&5
+echo "$as_me: error: qLibc library 1.0.0 or above must be installed. http://www.qdecoder.org" >&2;}
    { (exit 1); exit 1; }; }
 fi
 
 
 
-echo "$as_me:$LINENO: checking for main in -lqDecoder" >&5
-echo $ECHO_N "checking for main in -lqDecoder... $ECHO_C" >&6
-if test "${ac_cv_lib_qDecoder_main+set}" = set; then
+echo "$as_me:$LINENO: checking for main in -lqlibc" >&5
+echo $ECHO_N "checking for main in -lqlibc... $ECHO_C" >&6
+if test "${ac_cv_lib_qlibc_main+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
   ac_check_lib_save_LIBS=$LIBS
-LIBS="-lqDecoder  $LIBS"
+LIBS="-lqlibc  $LIBS"
 cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
 _ACEOF
@@ -3858,29 +3858,29 @@ if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
   ac_status=$?
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); }; }; then
-  ac_cv_lib_qDecoder_main=yes
+  ac_cv_lib_qlibc_main=yes
 else
   echo "$as_me: failed program was:" >&5
 sed 's/^/| /' conftest.$ac_ext >&5
 
-ac_cv_lib_qDecoder_main=no
+ac_cv_lib_qlibc_main=no
 fi
 rm -f conftest.err conftest.$ac_objext \
       conftest$ac_exeext conftest.$ac_ext
 LIBS=$ac_check_lib_save_LIBS
 fi
-echo "$as_me:$LINENO: result: $ac_cv_lib_qDecoder_main" >&5
-echo "${ECHO_T}$ac_cv_lib_qDecoder_main" >&6
-if test $ac_cv_lib_qDecoder_main = yes; then
+echo "$as_me:$LINENO: result: $ac_cv_lib_qlibc_main" >&5
+echo "${ECHO_T}$ac_cv_lib_qlibc_main" >&6
+if test $ac_cv_lib_qlibc_main = yes; then
   cat >>confdefs.h <<_ACEOF
-#define HAVE_LIBQDECODER 1
+#define HAVE_LIBQLIBC 1
 _ACEOF
 
-  LIBS="-lqDecoder $LIBS"
+  LIBS="-lqlibc $LIBS"
 
 else
-  { { echo "$as_me:$LINENO: error: qDecoder library 10.1.6 or above must be installed." >&5
-echo "$as_me: error: qDecoder library 10.1.6 or above must be installed." >&2;}
+  { { echo "$as_me:$LINENO: error: qLibc library 1.0.0 or above must be installed. http://www.qdecoder.org" >&5
+echo "$as_me: error: qLibc library 1.0.0 or above must be installed. http://www.qdecoder.org" >&2;}
    { (exit 1); exit 1; }; }
 fi
 
